language: node_js
node_js:
    - "node"
    - "8.11.1"
cache:
    directories:
        - "node_modules"
notifications:
    email:
        recipients:
            - "geekxing@163.com"
        on_success: always
        on_failure: always 
